### ISSUE TITLE
Plugin not available in the extension list.

### ISSUE THREAD

**Issue by ThMary** [irabinovitch/wp-datadog-rum#2]
Hi,

On my server, i have added the datadog-rum.php file to the /www/wp-content/plugins/datadog folder but the plugin is not avaiable in wordpress admin extensions (wp-admin/plugins.php). I use the 5.5.1 version.

**Comment by irabinovitch** [comment]
@ThMary Did you copy over the entire contents of the repo or just the  datadog-rum.php file?
You should be able to access it at /wp-admin/plugins.php?page=datadog-rum-config
